#!/usr/bin/env bash

declare -A curr_data=() # Use to store data. So that we can compaire it next second
declare -A prev_data=() 

#copy the data from the curr_data to prev_data
copy-data() {
	prev_data=();
	
	local key value
	for key in  "{!curr_data[@]}"; do 
		value=${curr_data[key]}
		prev_data[$key]=$value
	done	
}

read-proc() {
	local key user nice system idle iowait 
	local irq softriq steal guest guest_nice
	local busy 
	while read -r key user nice system idle iowait \
		irq softirq steal guest guest_nice; do 
		if [[ $key != cpu* ]]; then
			continue;
		elif [[ $key == "cpu" ]]; then
			continue;
		else
			busy=$(( user + nice + system + irq + softriq + steal + guest + nice))
			idle=$((idle + iowait))
			value="$busy $idle"
			curr_data[$key]=$value
		fi
	done < <(head -17 /proc/stat)
}

print-bar() {
	local key=$1
	local busy1 idle1 busy2 idle2
	read -r busy1 idle1 <<< "${prev_data[$key]}"
	read -r busy2 idle2 <<< "${curr_data[$key]}"
	
	local busy=$(( busy2 - busy1 ))
	local idle=$(( idle2 - idle1 ))
	local total=$(( busy + idle))

	local usage=$(( 1000 * busy / total)) # In bash there nothing called as the float
	local int=$((usage/10))
	local frac=$((usage % 10))
	perc="$int.$frac"	

	local bar_char='|'
	local empty_char='_'
	local length=50

	local num_bars=$(( usage * length / 1000 ))
	
	local i
	local s='['
	for ((i = 0; i < num_bars; i++)); do
		s+=$bar_char
	done
	for((i = num_bars; i < length; i++)); do
		s+=$empty_char
	done
	s+=']'

	echo  "$s $perc% $key"

}

#create visual graph to show data
create-visual() {
	local key
	for key in $(printf "%s\n" "${!curr_data[@]}" | sort -V); do
		print-bar "$key"
	done
	echo
}

#just to organize the things
main() {
	read-proc
	sleep 1
	while true; do
		copy-data
		read-proc
		create-visual
		sleep 1
	done
}

main
